### ISSUE TITLE
Turbo Drive compatibility

### ISSUE THREAD

**Issue by pomartel** [SimoTod/alpine-turbo-drive-adapter#25]
[Turbo Drive](https://turbo.hotwire.dev/handbook/drive) is set to replace Turbolinks and from what I read they are essentially the same except that Turbo Drive will be able to handle form submission in addition to regular links. I'm hoping the Alpine Turbolinks adapter (or maybe a fork?) can support Turbo Drive. I think a search and replace of "turbolinks" to "turbo" should hopefully be 95% of the job! 😅

**Comment by SimoTod** [comment]
Haha. It's probably not to distant from the reality. I haven't looked into it yet but it's probably just a matter of hooking into the right events. I'll post updates here once I have a better idea of the work required

**Comment by pjo336** [comment]
I'm goofing around in a lame attempt to get this to work, and it appears you have to change `turbolinks:whatever` to `turbo:whatever` as mentioned, but there is also a call to `event.data.newBody`, which now has become `event.detail.newbody`

I have no clue if that helps, but it seems to have me rolling again 👍

**Comment by SimoTod** [comment]
Thank you, @pjo336, it's a useful piece of information.

To anyone following this conversation, I think I'll release an upgrade at some point this week (I live in the UK, working for an online retailer shipping around the world and I've been a bit busy with all that Brexit shambles lately).

I was initially thinking of creating 2 branches (1.x supporting Turbolinks and 2.x supporting Turbo Drive) but the changes are really minimal so I'm now leaning towards a single branch supporting both (it would be just a few bytes more so size shouldn't be a concern). Does anyone have any preferences?

**Comment by HugoDF** [comment]
> changes are really minimal so I'm now leaning towards a single branch supporting both

sounds like a single branch/build that supports both will be simpler than having 2 mainline release branches + education piece around that

**Comment by ChrisZou** [comment]
Any progress on this?

**Comment by SimoTod** [comment]
I haven't had time to update the library yet. I'll post a message here when the new version has been tagged.

**Comment by SimoTod** [comment]
Before I tag a new release, can anyone check if https://cdn.jsdelivr.net/gh/SimoTod/alpine-turbolinks-adapter@feature/turbo-support/dist/alpine-turbo-adapter.min.js works as expected in their apps using Turbo, please?

FYI: The library will be renamed soon for consistency but it won't affect your applications.

**Comment by ChrisZou** [comment]
Hi @SimoTod , I tried with my app and it seems to be working quite well. You can see the [commit here](https://github.com/ChrisZou/geekweibo/commit/8572ed7219252e6739d0f3e1a3c00932395b2eb3). Thank you for this, and let me know if you need more tests.

**Comment by SimoTod** [comment]
I was trying to publish tonight but the name on npm is already taken by @wusher which I believe is maintaining his own fork. The relevant code is already in master but I need to think about a new name so ignore the readme for now, sorry.

**Comment by SimoTod** [comment]
Sorted. Please update your CDN link with the one in the readme (please note the npm library has changed as well). Thanks.

**Comment by wusher** [comment]
My apologies for taking the name. I was playing around with trying to get it working last night. I shouldn't have published and especially not with that name. I don't think I can fully release the package name but I'll try.

**Comment by SimoTod** [comment]
No worries. I've just added `-drive` to the name so it's not a problem.
